// src/vue/TodoList/Item.vue
<template>
  <div class="list-item" :style="{ transition: `opacity ${TRANSITION_SPEED}ms ease-in-out`, opacity: opacity.toString() }">
    <div :style="{ display: 'flex', flexDirection: 'row' }">
      <img v-if="content.img" :src="content.img" :style="{ width: '15%', height: 'auto', objectFit: 'cover', marginRight: '1%' }" />
      <div :style="{ display: 'flex', flexDirection: 'column', textAlign: 'left' }">
        <div :style="{fontSize: '150%'}">{{content.header}}</div>
        <div v-if="content.subheader" :style="{fontSize: '75%'}">{{content.subheader}}</div>
      </div>
    </div>
    <div @click="removeSelf" class="button">&times;</div>
  </div>
</template>
<script>
export default {
  props: {
    content: Object
  },
  created() {
    this.TRANSITION_SPEED = 200;
  },
  data() {
    return {
      opacity: 1
    }
  },
  methods: {
    removeSelf() {
      setTimeout(() => this.$emit('remove', this.content.id), this.TRANSITION_SPEED);
      this.$data.opacity = 0;
    }
  }
}
</script>

// src/react/TodoList/Item.js
import React, { useState } from 'react';
const TRANSITION_SPEED = 200;
const Item = ({ data, style, removeSelf, ...props }) => {
  let [opacity, setOpacity] = useState(1);
  return (<div className="list-item" style={{ transition: `opacity ${TRANSITION_SPEED}ms ease-in-out`, opacity: opacity.toString(), ...style }} {...props}>
    <div style={{ display: 'flex', flexDirection: 'row' }}>
      {data.img && <img src={data.img} style={{ width: '15%', height: 'auto', objectFit: 'cover', marginRight: '1%' }} />}
      <div style={{ display: 'flex', flexDirection: 'column', textAlign: 'left' }}>
        <div style={{fontSize: '150%'}}>{data.header}</div>
        {data.subheader && <div style={{fontSize: '75%'}}>{data.subheader}</div>}
      </div>
    </div>
    <div onClick={() => {
      setTimeout(removeSelf, TRANSITION_SPEED);
      setOpacity(0);
    }} className="button">&times;</div>
  </div>);
};
export default Item;
